version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0

    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore

      - run:
          name: Build SDK
          command: dotnet build -c Release -o out
      - run:
          name: Install Zip
          command: "apt-get update && apt-get install zip -y"
      - run:
          name: Zip artifacts
          command: |
                    mkdir /tmp/artifacts
                    zip -ur /tmp/artifacts/artifacts.zip out
                   |
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts.zip