version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0

    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore

      - run:
          name: Build SDK
          command: dotnet build -c Release -o out
      - run:
          name: Install Zip
          command: apt-get install zip
      - run:
          name: Zip artifacts
          command: zip -ur artifacts.zip out
      - store_artifacts:
          path: /project/artifacts.zip
          destination: artifacts.zip