version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0

    steps:
      - checkout

      - run:
          name: Restore
          command: dotnet restore

      - run:
          name: Build SDK
          command: dotnet build -c Release -o out